### ISSUE TITLE
2017 Data Invalid

### ISSUE THREAD

**Issue by spencerthayer** [spencerthayer/NCAA-Predictions#2]
When changing the `prediction_year` value to `2017` on line [23](https://github.com/spencerthayer/NCAA-Predictions/blob/master/NCAA.py#L23) the 2017 data breaks the script.
```
Building season data.
  Traceback (most recent call last):
  File "NCAA.py", line 54, in get_elo
    return team_elos[season][team]
KeyError: 2017
```
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NCAA.py", line 58, in get_elo
    team_elos[season][team] = team_elos[season-1][team]
KeyError: 2017
```
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NCAA.py", line 224, in <module>
    X, Y = build_season_data(all_data)
  File "NCAA.py", line 134, in build_season_data
    team_1_elo = get_elo(row['Season'], row['Wteam'])
  File "NCAA.py", line 62, in get_elo
    team_elos[season][team] = base_elo
KeyError: 2017
```

**Comment by spencerthayer** [comment]
[Here is](https://blog.starters.co/this-is-how-i-used-machine-learning-to-accurately-predict-villanova-to-win-the-2016-march-madness-ba5c074f1583#.4qa3keom9) an explanation of how this works from the author.

**Comment by spencerthayer** [comment]
The authors of the 2017 dataset seem to have knowingly changed the formatting a little. I have looked at the relevant files from the 2016 and 2017 directories and find nothing out of place. In other words, the structure of the CSV files are in order and consistent. The values of the data itself must be what is different. However, the explanation from the data authors is lacking. I have inquired as to the precise nature of the difference in the following discussion threads.

- [Now Open for 2017 Predictions (Stage 2)](https://www.kaggle.com/c/march-machine-learning-mania-2017/discussion/29989#167264)
- [ADDITIONAL DATA - Preliminary Results from Current Season](https://www.kaggle.com/c/march-machine-learning-mania-2017/discussion/28377#167272)

**Comment by spencerthayer** [comment]
The only CSV files used in either the 2016 or 2017 data directories are the following.

- Teams.csv
- RegularSeasonDetailedResults.csv
- TourneyDetailedResults.csv
- TourneySeeds.csv

**Comment by rbarghou** [comment]
I think this relates to the `initialize_data` function

```python
def initialize_data():
    for i in range(1985, 2017):
       ...
```

The range is off by 1, after incrementing the 2016 -> 2017 in the "prediction year" the range should have been updated in the initialization code as well.

**Comment by rbarghou** [comment]
addressed by PR https://github.com/spencerthayer/NCAA-Predictions/pull/5

**Comment by spencerthayer** [comment]
Future proofed this problem.
```python
def initialize_data():
    for i in range(1985, prediction_year+1):
    ...
```
